export const vaccines = [
  {
    id: 1,
    name: 'Rabies',
    description: 'Previene la rabia en perros y gatos',
    descripcionExtensa: 'La vacuna contra la rabia es una vacuna esencial para proteger a tu mascota contra una enfermedad mortal transmitida por la mordedura de animales infectados.',
    efectosSecundarios: 'Algunos efectos secundarios comunes pueden incluir dolor en el sitio de la inyección, letargo o pérdida de apetito temporal.',
    edadMinima: '12 semanas',
    mascotasAplicacion: 'Perros y gatos',
    image: 'https://salud.edomex.gob.mx/isem/imagenes/temas_programas/t_invernal/vacuna_covid2.png',
  },
  {
    id: 2,
    name: 'Parvovirus',
    description: 'Previene el parvovirus en perros',
    descripcionExtensa: 'La vacuna contra el parvovirus es crucial para proteger a los cachorros y perros adultos contra una enfermedad altamente contagiosa y potencialmente mortal.',
    efectosSecundarios: 'Los efectos secundarios pueden incluir hinchazón o enrojecimiento en el sitio de la inyección, letargo o fiebre.',
    edadMinima: '6 semanas',
    mascotasAplicacion: 'Perros',
    image: 'https://salud.edomex.gob.mx/isem/imagenes/temas_programas/t_invernal/vacuna_covid2.png',
  },
  {
    id: 3,
    name: 'FIV',
    description: 'Previene el virus de la inmunodeficiencia felina en gatos',
    descripcionExtensa: 'La vacuna contra el virus de la inmunodeficiencia felina (FIV) ayuda a prevenir una enfermedad grave que debilita el sistema inmunológico de los gatos, similar al VIH en humanos.',
    efectosSecundarios: 'Los efectos secundarios pueden incluir dolor o hinchazón en el sitio de la inyección, letargo o fiebre.',
    edadMinima: '8 semanas',
    mascotasAplicacion: 'Gatos',
    image: 'https://salud.edomex.gob.mx/isem/imagenes/temas_programas/t_invernal/vacuna_covid2.png',
  },
  {
    id: 4,
    name: 'Moquillo',
    description: 'Previene el moquillo en perros',
    descripcionExtensa: 'El moquillo es una enfermedad viral altamente contagiosa que puede causar síntomas graves y, en casos graves, la muerte en perros no vacunados.',
    efectosSecundarios: 'Los efectos secundarios pueden incluir hinchazón o enrojecimiento en el sitio de la inyección, letargo o fiebre.',
    edadMinima: '6 semanas',
    mascotasAplicacion: 'Perros',
    image: 'https://salud.edomex.gob.mx/isem/imagenes/temas_programas/t_invernal/vacuna_covid2.png',
  },
  {
    id: 5,
    name: 'Leptospirosis',
    description: 'Previene la leptospirosis en perros',
    descripcionExtensa: 'La leptospirosis es una enfermedad bacteriana transmitida por animales que puede afectar tanto a perros como a humanos. La vacuna es especialmente importante para perros que tienen un alto riesgo de exposición.',
    efectosSecundarios: 'Los efectos secundarios pueden incluir letargo, fiebre o reacción en el sitio de la inyección.',
    edadMinima: '12 semanas',
    mascotasAplicacion: 'Perros',
    image: 'https://salud.edomex.gob.mx/isem/imagenes/temas_programas/t_invernal/vacuna_covid2.png',
  },
  {
    id: 6,
    name: 'Bordetella',
    description: 'Previene la tos de las perreras en perros',
    descripcionExtensa: 'La tos de las perreras es una enfermedad altamente contagiosa que afecta las vías respiratorias de los perros. La vacuna ayuda a prevenir la propagación de la enfermedad en entornos donde los perros están en contacto cercano.',
    efectosSecundarios: 'Los efectos secundarios pueden incluir secreción nasal, tos leve o fiebre.',
    edadMinima: '6 semanas',
    mascotasAplicacion: 'Perros',
    image: 'https://salud.edomex.gob.mx/isem/imagenes/temas_programas/t_invernal/vacuna_covid2.png',
  },
  {
    id: 7,
    name: 'Panleucopenia',
    description: 'Previene la panleucopenia felina en gatos',
    descripcionExtensa: 'La panleucopenia felina, también conocida como parvovirus felino, es una enfermedad viral grave que afecta a los gatos. La vacuna es fundamental para proteger a los gatos contra esta enfermedad potencialmente mortal.',
    efectosSecundarios: 'Los efectos secundarios pueden incluir letargo, fiebre o reacción en el sitio de la inyección.',
    edadMinima: '8 semanas',
    mascotasAplicacion: 'Gatos',
    image: 'https://salud.edomex.gob.mx/isem/imagenes/temas_programas/t_invernal/vacuna_covid2.png',
  },
  {
    id: 8,
    name: 'Calicivirus',
    description: 'Previene el calicivirus felino en gatos',
    descripcionExtensa: 'El calicivirus felino es una enfermedad respiratoria común en gatos que puede causar síntomas como fiebre, estornudos y úlceras en la boca. La vacunación es importante para prevenir la propagación del virus.',
    efectosSecundarios: 'Los efectos secundarios pueden incluir letargo, fiebre o reacción en el sitio de la inyección.',
    edadMinima: '8 semanas',
    mascotasAplicacion: 'Gatos',
    image: 'https://salud.edomex.gob.mx/isem/imagenes/temas_programas/t_invernal/vacuna_covid2.png',
  },
  {
    id: 9,
    name: 'Rinotraqueitis',
    description: 'Previene la rinotraqueitis viral felina en gatos',
    descripcionExtensa: 'La rinotraqueitis viral felina es una infección respiratoria común en gatos que puede causar síntomas graves. La vacuna es fundamental para proteger a los gatos contra esta enfermedad contagiosa.',
    efectosSecundarios: 'Los efectos secundarios pueden incluir letargo, fiebre o reacción en el sitio de la inyección.',
    edadMinima: '8 semanas',
    mascotasAplicacion: 'Gatos',
    image: 'https://salud.edomex.gob.mx/isem/imagenes/temas_programas/t_invernal/vacuna_covid2.png',
  },
  // Agrega más vacunas aquí
];
